name: Deploy React App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        
    - name: Install dependencies
      working-directory: ./frontend
      run: |
        npm install --legacy-peer-deps
        npm install gh-pages --save-dev
        
    - name: Build and deploy
      working-directory: ./frontend
      run: |
        npm run deploy
      env:
        CI: false
